name: frontendapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.2
  provider: ^6.0.5
  intl: ^0.17.0
  http: ^0.13.6
  email_validator: ^3.0.0
  url_launcher: ^6.1.11
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  shared_preferences: ^2.3.2
  image_picker: ^0.8.7+4
  permission_handler: ^11.2.0
  mime: ^1.0.0
  http_parser: ^4.0.0
  flutter_cache_manager: ^3.3.1
  webview_flutter: ^4.8.0
  crypto: ^3.0.3
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/bear.jpg
    - assets/images/logo-bear.png
    - assets/images/login_banner.png
    - assets/images/momo_icon.png
    - assets/images/vnpay_icon.png
    - assets/images/zalopay_icon.png
    - assets/images/shopeepay_icon.png
    - assets/images/cinemas/cinema_1_1746214967186.jpg
    - assets/images/cinemas/cinema_2_1746215174736.jpg
    - assets/images/cinemas/cinema_3_1746215224604.jpg
    - assets/images/cinemas/cinema_4_1746375169224.jpg
    - assets/images/cinemas/cinema_5_1746215401993.jpg
    - assets/images/cinemas/cinema_6_1746375325231.jpg
    - assets/images/cinemas/cinema_7_1746215524120.jpg
    - assets/images/cinemas/cinema_8_1746215129247.jpg
    - assets/images/cinemas/cinema_9_1746215628582.jpg
    - assets/images/cinemas/cinema_9_1746375448482.jpg
    - assets/images/cinemas/cinema_10_1746375548086.jpg
    - assets/images/cinemas/cinema_11_1746375599036.jpg
    - assets/images/cinemas/cinema_12_1746375758125.jpg
    - assets/images/cinemas/cinema_13_1746375846069.jpg
    - assets/images/cinemas/cinema_14_1746375944257.jpg
    - assets/images/cinemas/cinema_15_1746376009746.jpg
    - assets/images/cinemas/cinema_16_1746376125934.jpg
    - assets/images/cinemas/cinema_17_1746376188767.jpg
    - assets/images/cinemas/cinema_18_1746376268601.jpg
    - assets/images/cinemas/cinema_19_1746376314673.jpg
    - assets/images/cinemas/cinema_20_1746376394994.jpg
    - assets/images/cinemas/cinema_21_1746376448605.jpg
    - assets/images/cinemas/cinema_22_1746376485825.jpg
    - assets/images/cinemas/cinema_23_1746376523036.jpg
    - assets/images/cinemas/cinema_24_1746376581868.jpg